import React from 'react';
import { Award, Sparkles } from 'lucide-react';
import { SectionCard } from '@/components/common/SectionCard';
import { ProgressTrack } from '@/components/common/ProgressTrack';
import { CertificateTable } from '@/components/certificates/CertificateTable';
import { certificatesMockData, certificationTracksMockData } from '@/data/certificates';

export const CertificatesPage: React.FC = () => {
  return (
    <div className="space-y-8 animate-fadeIn">
      {/* Page Header */}
      <div>
        <h1 className="font-heading text-2xl md:text-3xl font-bold text-text mb-2">Certifications & Records</h1>
        <p className="text-text/70 text-sm max-w-2xl">
          Review your earned credentials, download official transcripts, and monitor in-progress certification programs.
        </p>
      </div>

      {/* Overview stats block (Premium style) */}
      <div className="bg-[#0F4C81]/5 border border-primary/10 rounded-sm p-6 flex flex-col md:flex-row justify-between gap-6">
        <div className="flex items-start gap-4">
          <div className="p-3 bg-primary text-white rounded-sm">
            <Award size={28} />
          </div>
          <div>
            <h2 className="font-heading font-bold text-lg text-text">Official Transcripts & Credentials</h2>
            <p className="text-text/70 text-xs sm:text-sm mt-1 max-w-xl">
              All certificates generated by the Executive Institute are cryptographically signed and verifiable.
            </p>
          </div>
        </div>
        <div className="flex gap-8 shrink-0 text-center md:text-left self-center md:self-auto">
          <div>
            <div className="text-2xl font-bold text-primary font-heading">3</div>
            <div className="text-[10px] font-bold text-text/50 uppercase tracking-wider">Earned Credentials</div>
          </div>
          <div className="h-10 w-px bg-gray-200 self-center" />
          <div>
            <div className="text-2xl font-bold text-primary font-heading">42</div>
            <div className="text-[10px] font-bold text-text/50 uppercase tracking-wider">CPD Credits Approved</div>
          </div>
        </div>
      </div>

      {/* Grid containing Active Tracks and Certificate List */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 items-start">
        {/* Active certification tracks (1/3 cols) */}
        <div className="lg:col-span-1">
          <SectionCard title="Active Tracks" className="h-full">
            <div className="p-6 space-y-6">
              {certificationTracksMockData.map((track) => (
                <div key={track.id} className="pb-6 border-b border-gray-100 last:border-0 last:pb-0">
                  <ProgressTrack
                    title={track.title}
                    subtitle={track.moduleProgressLabel}
                    percentComplete={track.percentComplete}
                  />
                  <div className="mt-3 text-[11px] text-text/50 font-semibold flex items-center gap-1.5">
                    <Sparkles size={12} className="text-primary" />
                    <span>Eligible for 15 CPD Credits upon completion</span>
                  </div>
                </div>
              ))}
            </div>
          </SectionCard>
        </div>

        {/* Earned Credentials list (2/3 cols) */}
        <div className="lg:col-span-2">
          <h3 className="font-heading font-bold text-lg text-text mb-4">Earned Credentials</h3>
          {certificatesMockData.length > 0 ? (
            <CertificateTable certificates={certificatesMockData} />
          ) : (
            <div className="bg-white border border-gray-200 rounded-sm shadow-sm p-12 text-center text-text/50">
              <Award size={48} className="mx-auto mb-4 opacity-30 text-primary" />
              <h4 className="font-heading font-bold text-base text-text mb-1">No Credentials Earned Yet</h4>
              <p className="text-sm">Complete your active tracks to receive official digital certifications.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
export default CertificatesPage;
